# Generated by Django 5.2.7 on 2025-10-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True, verbose_name='Numero Camera')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Camera')),
                ('room_type', models.CharField(choices=[('SGL', 'Singola'), ('DBL', 'Doppia'), ('SUI', 'Suite')], max_length=3, verbose_name='Tipo Camera')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prezzo per Notte')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacità')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponibile')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Camere',
            },
        ),
    ]
